basePath: /
host: localhost:8080
info:
  contact: {}
  description: Sample template-go service with Swagger
  title: Template Go API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Hello World endpoint
      tags:
      - Root
swagger: "2.0"
